server:
  port: 8090

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: circuitbreaker_route
              uri: http://localhost:8080
              predicates:
                - Path=/status/504
              filters:
                - name: CircuitBreaker
                  args:
                    name: sampleCircuitBreaker
                    fallbackUri: forward:/fallback-circuitbreaker
            - id: circuitbreaker_route2
              uri: http://localhost:8081
              predicates:
                - Path=/error-method
              filters:
                - name: CircuitBreaker
                  args:
                    name: sampleCircuitBreaker
                    fallbackUri: forward:/fallback-circuitbreaker
            - id: retry_test
              uri: http://localhost:8080
              predicates:
                - Path=/status/502
              filters:
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY
                    methods: GET,POST
                    backoff:
                      firstBackoff: 500ms
                      maxBackoff: 1000ms
                      factor: 2
                      basedOnPreviousValue: false
            - id: request_rate_limiter
              uri: http://localhost:8080
              predicates:
                - Path=/rate-limit/get/**
              filters:
                - name: RequestRateLimiter
                  args:
                    #redis-rate-limiter.replenishRate: 2        # 2 tokens/sec → 120/min
                    #redis-rate-limiter.burstCapacity: 120
                    redis-rate-limiter.replenishRate: 1        # 1 tokens/sec → 60/min
                    redis-rate-limiter.burstCapacity: 60
                    key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: 10.220.14.125
      port: 6380
      password: password

resilience4j:
  circuitbreaker:
    instances:
      sampleCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s


management:
  endpoints:
    web:
      exposure:
        include: "*"
